// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MovieControl.proto

package CinemaProject.service1;

public interface PauseMovieResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CinemaProject.PauseMovieResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string status = 1;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 1;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
