// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MovieControl.proto

package CinemaProject.service1;

public interface PlayMovieRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CinemaProject.PlayMovieRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 screenId = 1;</code>
   */
  int getScreenId();
}
