// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MovieControl.proto

package CinemaProject.service1;

public final class Service1Impl {
  private Service1Impl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CinemaProject_PlayMovieRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CinemaProject_PlayMovieRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CinemaProject_PlayMovieResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CinemaProject_PlayMovieResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CinemaProject_PauseMovieRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CinemaProject_PauseMovieRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CinemaProject_PauseMovieResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CinemaProject_PauseMovieResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CinemaProject_MonitorPlaybackRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CinemaProject_MonitorPlaybackRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CinemaProject_MonitorPlaybackResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CinemaProject_MonitorPlaybackResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022MovieControl.proto\022\rCinemaProject\"$\n\020P" +
      "layMovieRequest\022\020\n\010screenId\030\001 \001(\005\"#\n\021Pla" +
      "yMovieResponse\022\016\n\006status\030\001 \001(\t\"%\n\021PauseM" +
      "ovieRequest\022\020\n\010screenId\030\001 \001(\005\"$\n\022PauseMo" +
      "vieResponse\022\016\n\006status\030\001 \001(\t\"*\n\026MonitorPl" +
      "aybackRequest\022\020\n\010screenId\030\001 \001(\005\")\n\027Monit" +
      "orPlaybackResponse\022\016\n\006status\030\001 \001(\t2\223\002\n\014M" +
      "ovieControl\022N\n\tPlayMovie\022\037.CinemaProject" +
      ".PlayMovieRequest\032 .CinemaProject.PlayMo" +
      "vieResponse\022Q\n\nPauseMovie\022 .CinemaProjec" +
      "t.PauseMovieRequest\032!.CinemaProject.Paus" +
      "eMovieResponse\022`\n\017MonitorPlayback\022%.Cine" +
      "maProject.MonitorPlaybackRequest\032&.Cinem" +
      "aProject.MonitorPlaybackResponseB(\n\026Cine" +
      "maProject.service1B\014Service1ImplP\001b\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_CinemaProject_PlayMovieRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CinemaProject_PlayMovieRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CinemaProject_PlayMovieRequest_descriptor,
        new java.lang.String[] { "ScreenId", });
    internal_static_CinemaProject_PlayMovieResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CinemaProject_PlayMovieResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CinemaProject_PlayMovieResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_CinemaProject_PauseMovieRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_CinemaProject_PauseMovieRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CinemaProject_PauseMovieRequest_descriptor,
        new java.lang.String[] { "ScreenId", });
    internal_static_CinemaProject_PauseMovieResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_CinemaProject_PauseMovieResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CinemaProject_PauseMovieResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_CinemaProject_MonitorPlaybackRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_CinemaProject_MonitorPlaybackRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CinemaProject_MonitorPlaybackRequest_descriptor,
        new java.lang.String[] { "ScreenId", });
    internal_static_CinemaProject_MonitorPlaybackResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_CinemaProject_MonitorPlaybackResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CinemaProject_MonitorPlaybackResponse_descriptor,
        new java.lang.String[] { "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
