// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EnvironmentControl.proto

package CinemaProject.service2;

public final class Service2Impl {
  private Service2Impl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CinemaProject_SetTemperatureRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CinemaProject_SetTemperatureRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CinemaProject_SetTemperatureResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CinemaProject_SetTemperatureResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CinemaProject_SetVolumeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CinemaProject_SetVolumeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CinemaProject_SetVolumeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CinemaProject_SetVolumeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CinemaProject_SetLightingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CinemaProject_SetLightingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CinemaProject_SetLightingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CinemaProject_SetLightingResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030EnvironmentControl.proto\022\rCinemaProjec" +
      "t\">\n\025SetTemperatureRequest\022\023\n\013temperatur" +
      "e\030\001 \001(\002\022\020\n\010screenId\030\002 \001(\005\"(\n\026SetTemperat" +
      "ureResponse\022\016\n\006status\030\001 \001(\t\"9\n\020SetVolume" +
      "Request\022\023\n\013volumeLevel\030\001 \001(\005\022\020\n\010screenId" +
      "\030\002 \001(\005\"#\n\021SetVolumeResponse\022\016\n\006status\030\001 " +
      "\001(\t\"=\n\022SetLightingRequest\022\025\n\rlightingLev" +
      "el\030\001 \001(\005\022\020\n\010screenId\030\002 \001(\005\"%\n\023SetLightin" +
      "gResponse\022\016\n\006status\030\001 \001(\t2\231\002\n\022Environmen" +
      "tControl\022]\n\016SetTemperature\022$.CinemaProje" +
      "ct.SetTemperatureRequest\032%.CinemaProject" +
      ".SetTemperatureResponse\022N\n\tSetVolume\022\037.C" +
      "inemaProject.SetVolumeRequest\032 .CinemaPr" +
      "oject.SetVolumeResponse\022T\n\013SetLighting\022!" +
      ".CinemaProject.SetLightingRequest\032\".Cine" +
      "maProject.SetLightingResponseB(\n\026CinemaP" +
      "roject.service2B\014Service2ImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_CinemaProject_SetTemperatureRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CinemaProject_SetTemperatureRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CinemaProject_SetTemperatureRequest_descriptor,
        new java.lang.String[] { "Temperature", "ScreenId", });
    internal_static_CinemaProject_SetTemperatureResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CinemaProject_SetTemperatureResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CinemaProject_SetTemperatureResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_CinemaProject_SetVolumeRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_CinemaProject_SetVolumeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CinemaProject_SetVolumeRequest_descriptor,
        new java.lang.String[] { "VolumeLevel", "ScreenId", });
    internal_static_CinemaProject_SetVolumeResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_CinemaProject_SetVolumeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CinemaProject_SetVolumeResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_CinemaProject_SetLightingRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_CinemaProject_SetLightingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CinemaProject_SetLightingRequest_descriptor,
        new java.lang.String[] { "LightingLevel", "ScreenId", });
    internal_static_CinemaProject_SetLightingResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_CinemaProject_SetLightingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CinemaProject_SetLightingResponse_descriptor,
        new java.lang.String[] { "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
