// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EnvironmentControl.proto

package CinemaProject.service2;

public interface SetLightingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CinemaProject.SetLightingRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 lightingLevel = 1;</code>
   */
  int getLightingLevel();

  /**
   * <code>int32 screenId = 2;</code>
   */
  int getScreenId();
}
