// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EnvironmentControl.proto

package CinemaProject.service2;

/**
 * Protobuf type {@code CinemaProject.SetLightingRequest}
 */
public  final class SetLightingRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:CinemaProject.SetLightingRequest)
    SetLightingRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SetLightingRequest.newBuilder() to construct.
  private SetLightingRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SetLightingRequest() {
    lightingLevel_ = 0;
    screenId_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SetLightingRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            lightingLevel_ = input.readInt32();
            break;
          }
          case 16: {

            screenId_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return CinemaProject.service2.Service2Impl.internal_static_CinemaProject_SetLightingRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return CinemaProject.service2.Service2Impl.internal_static_CinemaProject_SetLightingRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            CinemaProject.service2.SetLightingRequest.class, CinemaProject.service2.SetLightingRequest.Builder.class);
  }

  public static final int LIGHTINGLEVEL_FIELD_NUMBER = 1;
  private int lightingLevel_;
  /**
   * <code>int32 lightingLevel = 1;</code>
   */
  public int getLightingLevel() {
    return lightingLevel_;
  }

  public static final int SCREENID_FIELD_NUMBER = 2;
  private int screenId_;
  /**
   * <code>int32 screenId = 2;</code>
   */
  public int getScreenId() {
    return screenId_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (lightingLevel_ != 0) {
      output.writeInt32(1, lightingLevel_);
    }
    if (screenId_ != 0) {
      output.writeInt32(2, screenId_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (lightingLevel_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, lightingLevel_);
    }
    if (screenId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, screenId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof CinemaProject.service2.SetLightingRequest)) {
      return super.equals(obj);
    }
    CinemaProject.service2.SetLightingRequest other = (CinemaProject.service2.SetLightingRequest) obj;

    boolean result = true;
    result = result && (getLightingLevel()
        == other.getLightingLevel());
    result = result && (getScreenId()
        == other.getScreenId());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + LIGHTINGLEVEL_FIELD_NUMBER;
    hash = (53 * hash) + getLightingLevel();
    hash = (37 * hash) + SCREENID_FIELD_NUMBER;
    hash = (53 * hash) + getScreenId();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static CinemaProject.service2.SetLightingRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CinemaProject.service2.SetLightingRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CinemaProject.service2.SetLightingRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CinemaProject.service2.SetLightingRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CinemaProject.service2.SetLightingRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CinemaProject.service2.SetLightingRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CinemaProject.service2.SetLightingRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static CinemaProject.service2.SetLightingRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static CinemaProject.service2.SetLightingRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static CinemaProject.service2.SetLightingRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static CinemaProject.service2.SetLightingRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static CinemaProject.service2.SetLightingRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(CinemaProject.service2.SetLightingRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code CinemaProject.SetLightingRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:CinemaProject.SetLightingRequest)
      CinemaProject.service2.SetLightingRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CinemaProject.service2.Service2Impl.internal_static_CinemaProject_SetLightingRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CinemaProject.service2.Service2Impl.internal_static_CinemaProject_SetLightingRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CinemaProject.service2.SetLightingRequest.class, CinemaProject.service2.SetLightingRequest.Builder.class);
    }

    // Construct using CinemaProject.service2.SetLightingRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      lightingLevel_ = 0;

      screenId_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return CinemaProject.service2.Service2Impl.internal_static_CinemaProject_SetLightingRequest_descriptor;
    }

    @java.lang.Override
    public CinemaProject.service2.SetLightingRequest getDefaultInstanceForType() {
      return CinemaProject.service2.SetLightingRequest.getDefaultInstance();
    }

    @java.lang.Override
    public CinemaProject.service2.SetLightingRequest build() {
      CinemaProject.service2.SetLightingRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public CinemaProject.service2.SetLightingRequest buildPartial() {
      CinemaProject.service2.SetLightingRequest result = new CinemaProject.service2.SetLightingRequest(this);
      result.lightingLevel_ = lightingLevel_;
      result.screenId_ = screenId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof CinemaProject.service2.SetLightingRequest) {
        return mergeFrom((CinemaProject.service2.SetLightingRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(CinemaProject.service2.SetLightingRequest other) {
      if (other == CinemaProject.service2.SetLightingRequest.getDefaultInstance()) return this;
      if (other.getLightingLevel() != 0) {
        setLightingLevel(other.getLightingLevel());
      }
      if (other.getScreenId() != 0) {
        setScreenId(other.getScreenId());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      CinemaProject.service2.SetLightingRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (CinemaProject.service2.SetLightingRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int lightingLevel_ ;
    /**
     * <code>int32 lightingLevel = 1;</code>
     */
    public int getLightingLevel() {
      return lightingLevel_;
    }
    /**
     * <code>int32 lightingLevel = 1;</code>
     */
    public Builder setLightingLevel(int value) {
      
      lightingLevel_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 lightingLevel = 1;</code>
     */
    public Builder clearLightingLevel() {
      
      lightingLevel_ = 0;
      onChanged();
      return this;
    }

    private int screenId_ ;
    /**
     * <code>int32 screenId = 2;</code>
     */
    public int getScreenId() {
      return screenId_;
    }
    /**
     * <code>int32 screenId = 2;</code>
     */
    public Builder setScreenId(int value) {
      
      screenId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 screenId = 2;</code>
     */
    public Builder clearScreenId() {
      
      screenId_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:CinemaProject.SetLightingRequest)
  }

  // @@protoc_insertion_point(class_scope:CinemaProject.SetLightingRequest)
  private static final CinemaProject.service2.SetLightingRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new CinemaProject.service2.SetLightingRequest();
  }

  public static CinemaProject.service2.SetLightingRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SetLightingRequest>
      PARSER = new com.google.protobuf.AbstractParser<SetLightingRequest>() {
    @java.lang.Override
    public SetLightingRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SetLightingRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SetLightingRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SetLightingRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public CinemaProject.service2.SetLightingRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

