// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EnvironmentControl.proto

package CinemaProject.service2;

public interface SetLightingResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CinemaProject.SetLightingResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string status = 1;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 1;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
