// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EnvironmentControl.proto

package CinemaProject.service2;

public interface SetTemperatureRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CinemaProject.SetTemperatureRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float temperature = 1;</code>
   */
  float getTemperature();

  /**
   * <code>int32 screenId = 2;</code>
   */
  int getScreenId();
}
