// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EnvironmentControl.proto

package CinemaProject.service2;

public interface SetVolumeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CinemaProject.SetVolumeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 volumeLevel = 1;</code>
   */
  int getVolumeLevel();

  /**
   * <code>int32 screenId = 2;</code>
   */
  int getScreenId();
}
