// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TicketingControl.proto

package CinemaProject.service3;

public interface GetMovieScheduleRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CinemaProject.GetMovieScheduleRequest)
    com.google.protobuf.MessageOrBuilder {
}
