// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TicketingControl.proto

package CinemaProject.service3;

/**
 * Protobuf type {@code CinemaProject.GetMovieScheduleResponse}
 */
public  final class GetMovieScheduleResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:CinemaProject.GetMovieScheduleResponse)
    GetMovieScheduleResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetMovieScheduleResponse.newBuilder() to construct.
  private GetMovieScheduleResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetMovieScheduleResponse() {
    movieSchedules_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetMovieScheduleResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              movieSchedules_ = new java.util.ArrayList<CinemaProject.service3.MovieSchedule>();
              mutable_bitField0_ |= 0x00000001;
            }
            movieSchedules_.add(
                input.readMessage(CinemaProject.service3.MovieSchedule.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        movieSchedules_ = java.util.Collections.unmodifiableList(movieSchedules_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return CinemaProject.service3.Service3Impl.internal_static_CinemaProject_GetMovieScheduleResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return CinemaProject.service3.Service3Impl.internal_static_CinemaProject_GetMovieScheduleResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            CinemaProject.service3.GetMovieScheduleResponse.class, CinemaProject.service3.GetMovieScheduleResponse.Builder.class);
  }

  public static final int MOVIESCHEDULES_FIELD_NUMBER = 1;
  private java.util.List<CinemaProject.service3.MovieSchedule> movieSchedules_;
  /**
   * <code>repeated .CinemaProject.MovieSchedule movieSchedules = 1;</code>
   */
  public java.util.List<CinemaProject.service3.MovieSchedule> getMovieSchedulesList() {
    return movieSchedules_;
  }
  /**
   * <code>repeated .CinemaProject.MovieSchedule movieSchedules = 1;</code>
   */
  public java.util.List<? extends CinemaProject.service3.MovieScheduleOrBuilder> 
      getMovieSchedulesOrBuilderList() {
    return movieSchedules_;
  }
  /**
   * <code>repeated .CinemaProject.MovieSchedule movieSchedules = 1;</code>
   */
  public int getMovieSchedulesCount() {
    return movieSchedules_.size();
  }
  /**
   * <code>repeated .CinemaProject.MovieSchedule movieSchedules = 1;</code>
   */
  public CinemaProject.service3.MovieSchedule getMovieSchedules(int index) {
    return movieSchedules_.get(index);
  }
  /**
   * <code>repeated .CinemaProject.MovieSchedule movieSchedules = 1;</code>
   */
  public CinemaProject.service3.MovieScheduleOrBuilder getMovieSchedulesOrBuilder(
      int index) {
    return movieSchedules_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < movieSchedules_.size(); i++) {
      output.writeMessage(1, movieSchedules_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < movieSchedules_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, movieSchedules_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof CinemaProject.service3.GetMovieScheduleResponse)) {
      return super.equals(obj);
    }
    CinemaProject.service3.GetMovieScheduleResponse other = (CinemaProject.service3.GetMovieScheduleResponse) obj;

    boolean result = true;
    result = result && getMovieSchedulesList()
        .equals(other.getMovieSchedulesList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getMovieSchedulesCount() > 0) {
      hash = (37 * hash) + MOVIESCHEDULES_FIELD_NUMBER;
      hash = (53 * hash) + getMovieSchedulesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static CinemaProject.service3.GetMovieScheduleResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CinemaProject.service3.GetMovieScheduleResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CinemaProject.service3.GetMovieScheduleResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CinemaProject.service3.GetMovieScheduleResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CinemaProject.service3.GetMovieScheduleResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CinemaProject.service3.GetMovieScheduleResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CinemaProject.service3.GetMovieScheduleResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static CinemaProject.service3.GetMovieScheduleResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static CinemaProject.service3.GetMovieScheduleResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static CinemaProject.service3.GetMovieScheduleResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static CinemaProject.service3.GetMovieScheduleResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static CinemaProject.service3.GetMovieScheduleResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(CinemaProject.service3.GetMovieScheduleResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code CinemaProject.GetMovieScheduleResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:CinemaProject.GetMovieScheduleResponse)
      CinemaProject.service3.GetMovieScheduleResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CinemaProject.service3.Service3Impl.internal_static_CinemaProject_GetMovieScheduleResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CinemaProject.service3.Service3Impl.internal_static_CinemaProject_GetMovieScheduleResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CinemaProject.service3.GetMovieScheduleResponse.class, CinemaProject.service3.GetMovieScheduleResponse.Builder.class);
    }

    // Construct using CinemaProject.service3.GetMovieScheduleResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getMovieSchedulesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (movieSchedulesBuilder_ == null) {
        movieSchedules_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        movieSchedulesBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return CinemaProject.service3.Service3Impl.internal_static_CinemaProject_GetMovieScheduleResponse_descriptor;
    }

    @java.lang.Override
    public CinemaProject.service3.GetMovieScheduleResponse getDefaultInstanceForType() {
      return CinemaProject.service3.GetMovieScheduleResponse.getDefaultInstance();
    }

    @java.lang.Override
    public CinemaProject.service3.GetMovieScheduleResponse build() {
      CinemaProject.service3.GetMovieScheduleResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public CinemaProject.service3.GetMovieScheduleResponse buildPartial() {
      CinemaProject.service3.GetMovieScheduleResponse result = new CinemaProject.service3.GetMovieScheduleResponse(this);
      int from_bitField0_ = bitField0_;
      if (movieSchedulesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          movieSchedules_ = java.util.Collections.unmodifiableList(movieSchedules_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.movieSchedules_ = movieSchedules_;
      } else {
        result.movieSchedules_ = movieSchedulesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof CinemaProject.service3.GetMovieScheduleResponse) {
        return mergeFrom((CinemaProject.service3.GetMovieScheduleResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(CinemaProject.service3.GetMovieScheduleResponse other) {
      if (other == CinemaProject.service3.GetMovieScheduleResponse.getDefaultInstance()) return this;
      if (movieSchedulesBuilder_ == null) {
        if (!other.movieSchedules_.isEmpty()) {
          if (movieSchedules_.isEmpty()) {
            movieSchedules_ = other.movieSchedules_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureMovieSchedulesIsMutable();
            movieSchedules_.addAll(other.movieSchedules_);
          }
          onChanged();
        }
      } else {
        if (!other.movieSchedules_.isEmpty()) {
          if (movieSchedulesBuilder_.isEmpty()) {
            movieSchedulesBuilder_.dispose();
            movieSchedulesBuilder_ = null;
            movieSchedules_ = other.movieSchedules_;
            bitField0_ = (bitField0_ & ~0x00000001);
            movieSchedulesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getMovieSchedulesFieldBuilder() : null;
          } else {
            movieSchedulesBuilder_.addAllMessages(other.movieSchedules_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      CinemaProject.service3.GetMovieScheduleResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (CinemaProject.service3.GetMovieScheduleResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<CinemaProject.service3.MovieSchedule> movieSchedules_ =
      java.util.Collections.emptyList();
    private void ensureMovieSchedulesIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        movieSchedules_ = new java.util.ArrayList<CinemaProject.service3.MovieSchedule>(movieSchedules_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        CinemaProject.service3.MovieSchedule, CinemaProject.service3.MovieSchedule.Builder, CinemaProject.service3.MovieScheduleOrBuilder> movieSchedulesBuilder_;

    /**
     * <code>repeated .CinemaProject.MovieSchedule movieSchedules = 1;</code>
     */
    public java.util.List<CinemaProject.service3.MovieSchedule> getMovieSchedulesList() {
      if (movieSchedulesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(movieSchedules_);
      } else {
        return movieSchedulesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .CinemaProject.MovieSchedule movieSchedules = 1;</code>
     */
    public int getMovieSchedulesCount() {
      if (movieSchedulesBuilder_ == null) {
        return movieSchedules_.size();
      } else {
        return movieSchedulesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .CinemaProject.MovieSchedule movieSchedules = 1;</code>
     */
    public CinemaProject.service3.MovieSchedule getMovieSchedules(int index) {
      if (movieSchedulesBuilder_ == null) {
        return movieSchedules_.get(index);
      } else {
        return movieSchedulesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .CinemaProject.MovieSchedule movieSchedules = 1;</code>
     */
    public Builder setMovieSchedules(
        int index, CinemaProject.service3.MovieSchedule value) {
      if (movieSchedulesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMovieSchedulesIsMutable();
        movieSchedules_.set(index, value);
        onChanged();
      } else {
        movieSchedulesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .CinemaProject.MovieSchedule movieSchedules = 1;</code>
     */
    public Builder setMovieSchedules(
        int index, CinemaProject.service3.MovieSchedule.Builder builderForValue) {
      if (movieSchedulesBuilder_ == null) {
        ensureMovieSchedulesIsMutable();
        movieSchedules_.set(index, builderForValue.build());
        onChanged();
      } else {
        movieSchedulesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .CinemaProject.MovieSchedule movieSchedules = 1;</code>
     */
    public Builder addMovieSchedules(CinemaProject.service3.MovieSchedule value) {
      if (movieSchedulesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMovieSchedulesIsMutable();
        movieSchedules_.add(value);
        onChanged();
      } else {
        movieSchedulesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .CinemaProject.MovieSchedule movieSchedules = 1;</code>
     */
    public Builder addMovieSchedules(
        int index, CinemaProject.service3.MovieSchedule value) {
      if (movieSchedulesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMovieSchedulesIsMutable();
        movieSchedules_.add(index, value);
        onChanged();
      } else {
        movieSchedulesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .CinemaProject.MovieSchedule movieSchedules = 1;</code>
     */
    public Builder addMovieSchedules(
        CinemaProject.service3.MovieSchedule.Builder builderForValue) {
      if (movieSchedulesBuilder_ == null) {
        ensureMovieSchedulesIsMutable();
        movieSchedules_.add(builderForValue.build());
        onChanged();
      } else {
        movieSchedulesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .CinemaProject.MovieSchedule movieSchedules = 1;</code>
     */
    public Builder addMovieSchedules(
        int index, CinemaProject.service3.MovieSchedule.Builder builderForValue) {
      if (movieSchedulesBuilder_ == null) {
        ensureMovieSchedulesIsMutable();
        movieSchedules_.add(index, builderForValue.build());
        onChanged();
      } else {
        movieSchedulesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .CinemaProject.MovieSchedule movieSchedules = 1;</code>
     */
    public Builder addAllMovieSchedules(
        java.lang.Iterable<? extends CinemaProject.service3.MovieSchedule> values) {
      if (movieSchedulesBuilder_ == null) {
        ensureMovieSchedulesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, movieSchedules_);
        onChanged();
      } else {
        movieSchedulesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .CinemaProject.MovieSchedule movieSchedules = 1;</code>
     */
    public Builder clearMovieSchedules() {
      if (movieSchedulesBuilder_ == null) {
        movieSchedules_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        movieSchedulesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .CinemaProject.MovieSchedule movieSchedules = 1;</code>
     */
    public Builder removeMovieSchedules(int index) {
      if (movieSchedulesBuilder_ == null) {
        ensureMovieSchedulesIsMutable();
        movieSchedules_.remove(index);
        onChanged();
      } else {
        movieSchedulesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .CinemaProject.MovieSchedule movieSchedules = 1;</code>
     */
    public CinemaProject.service3.MovieSchedule.Builder getMovieSchedulesBuilder(
        int index) {
      return getMovieSchedulesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .CinemaProject.MovieSchedule movieSchedules = 1;</code>
     */
    public CinemaProject.service3.MovieScheduleOrBuilder getMovieSchedulesOrBuilder(
        int index) {
      if (movieSchedulesBuilder_ == null) {
        return movieSchedules_.get(index);  } else {
        return movieSchedulesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .CinemaProject.MovieSchedule movieSchedules = 1;</code>
     */
    public java.util.List<? extends CinemaProject.service3.MovieScheduleOrBuilder> 
         getMovieSchedulesOrBuilderList() {
      if (movieSchedulesBuilder_ != null) {
        return movieSchedulesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(movieSchedules_);
      }
    }
    /**
     * <code>repeated .CinemaProject.MovieSchedule movieSchedules = 1;</code>
     */
    public CinemaProject.service3.MovieSchedule.Builder addMovieSchedulesBuilder() {
      return getMovieSchedulesFieldBuilder().addBuilder(
          CinemaProject.service3.MovieSchedule.getDefaultInstance());
    }
    /**
     * <code>repeated .CinemaProject.MovieSchedule movieSchedules = 1;</code>
     */
    public CinemaProject.service3.MovieSchedule.Builder addMovieSchedulesBuilder(
        int index) {
      return getMovieSchedulesFieldBuilder().addBuilder(
          index, CinemaProject.service3.MovieSchedule.getDefaultInstance());
    }
    /**
     * <code>repeated .CinemaProject.MovieSchedule movieSchedules = 1;</code>
     */
    public java.util.List<CinemaProject.service3.MovieSchedule.Builder> 
         getMovieSchedulesBuilderList() {
      return getMovieSchedulesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        CinemaProject.service3.MovieSchedule, CinemaProject.service3.MovieSchedule.Builder, CinemaProject.service3.MovieScheduleOrBuilder> 
        getMovieSchedulesFieldBuilder() {
      if (movieSchedulesBuilder_ == null) {
        movieSchedulesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            CinemaProject.service3.MovieSchedule, CinemaProject.service3.MovieSchedule.Builder, CinemaProject.service3.MovieScheduleOrBuilder>(
                movieSchedules_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        movieSchedules_ = null;
      }
      return movieSchedulesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:CinemaProject.GetMovieScheduleResponse)
  }

  // @@protoc_insertion_point(class_scope:CinemaProject.GetMovieScheduleResponse)
  private static final CinemaProject.service3.GetMovieScheduleResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new CinemaProject.service3.GetMovieScheduleResponse();
  }

  public static CinemaProject.service3.GetMovieScheduleResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetMovieScheduleResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetMovieScheduleResponse>() {
    @java.lang.Override
    public GetMovieScheduleResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetMovieScheduleResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetMovieScheduleResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetMovieScheduleResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public CinemaProject.service3.GetMovieScheduleResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

