// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TicketingControl.proto

package CinemaProject.service3;

public interface GetMovieScheduleResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CinemaProject.GetMovieScheduleResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .CinemaProject.MovieSchedule movieSchedules = 1;</code>
   */
  java.util.List<CinemaProject.service3.MovieSchedule> 
      getMovieSchedulesList();
  /**
   * <code>repeated .CinemaProject.MovieSchedule movieSchedules = 1;</code>
   */
  CinemaProject.service3.MovieSchedule getMovieSchedules(int index);
  /**
   * <code>repeated .CinemaProject.MovieSchedule movieSchedules = 1;</code>
   */
  int getMovieSchedulesCount();
  /**
   * <code>repeated .CinemaProject.MovieSchedule movieSchedules = 1;</code>
   */
  java.util.List<? extends CinemaProject.service3.MovieScheduleOrBuilder> 
      getMovieSchedulesOrBuilderList();
  /**
   * <code>repeated .CinemaProject.MovieSchedule movieSchedules = 1;</code>
   */
  CinemaProject.service3.MovieScheduleOrBuilder getMovieSchedulesOrBuilder(
      int index);
}
