// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TicketingControl.proto

package CinemaProject.service3;

public interface MovieScheduleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CinemaProject.MovieSchedule)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string title = 1;</code>
   */
  java.lang.String getTitle();
  /**
   * <code>string title = 1;</code>
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>string movieId = 2;</code>
   */
  java.lang.String getMovieId();
  /**
   * <code>string movieId = 2;</code>
   */
  com.google.protobuf.ByteString
      getMovieIdBytes();

  /**
   * <code>string showtime = 3;</code>
   */
  java.lang.String getShowtime();
  /**
   * <code>string showtime = 3;</code>
   */
  com.google.protobuf.ByteString
      getShowtimeBytes();

  /**
   * <code>int32 screenId = 4;</code>
   */
  int getScreenId();
}
