// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TicketingControl.proto

package CinemaProject.service3;

public interface PurchaseTicketResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CinemaProject.PurchaseTicketResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string status = 1;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 1;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>int32 ticketId = 2;</code>
   */
  int getTicketId();
}
