// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TicketingControl.proto

package CinemaProject.service3;

public interface PurchaseTicketRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CinemaProject.PurchaseTicketRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string movieId = 1;</code>
   */
  java.lang.String getMovieId();
  /**
   * <code>string movieId = 1;</code>
   */
  com.google.protobuf.ByteString
      getMovieIdBytes();

  /**
   * <code>int32 quantity = 2;</code>
   */
  int getQuantity();
}
