// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TicketingControl.proto

package CinemaProject.service3;

public interface ReserveSeatRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CinemaProject.ReserveSeatRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 ticketId = 1;</code>
   */
  int getTicketId();
}
