// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TicketingControl.proto

package CinemaProject.service3;

/**
 * Protobuf type {@code CinemaProject.ReserveSeatRequest}
 */
public  final class ReserveSeatRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:CinemaProject.ReserveSeatRequest)
    ReserveSeatRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ReserveSeatRequest.newBuilder() to construct.
  private ReserveSeatRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ReserveSeatRequest() {
    ticketId_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ReserveSeatRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            ticketId_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return CinemaProject.service3.Service3Impl.internal_static_CinemaProject_ReserveSeatRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return CinemaProject.service3.Service3Impl.internal_static_CinemaProject_ReserveSeatRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            CinemaProject.service3.ReserveSeatRequest.class, CinemaProject.service3.ReserveSeatRequest.Builder.class);
  }

  public static final int TICKETID_FIELD_NUMBER = 1;
  private int ticketId_;
  /**
   * <code>int32 ticketId = 1;</code>
   */
  public int getTicketId() {
    return ticketId_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (ticketId_ != 0) {
      output.writeInt32(1, ticketId_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (ticketId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, ticketId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof CinemaProject.service3.ReserveSeatRequest)) {
      return super.equals(obj);
    }
    CinemaProject.service3.ReserveSeatRequest other = (CinemaProject.service3.ReserveSeatRequest) obj;

    boolean result = true;
    result = result && (getTicketId()
        == other.getTicketId());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TICKETID_FIELD_NUMBER;
    hash = (53 * hash) + getTicketId();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static CinemaProject.service3.ReserveSeatRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CinemaProject.service3.ReserveSeatRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CinemaProject.service3.ReserveSeatRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CinemaProject.service3.ReserveSeatRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CinemaProject.service3.ReserveSeatRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CinemaProject.service3.ReserveSeatRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CinemaProject.service3.ReserveSeatRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static CinemaProject.service3.ReserveSeatRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static CinemaProject.service3.ReserveSeatRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static CinemaProject.service3.ReserveSeatRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static CinemaProject.service3.ReserveSeatRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static CinemaProject.service3.ReserveSeatRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(CinemaProject.service3.ReserveSeatRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code CinemaProject.ReserveSeatRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:CinemaProject.ReserveSeatRequest)
      CinemaProject.service3.ReserveSeatRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CinemaProject.service3.Service3Impl.internal_static_CinemaProject_ReserveSeatRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CinemaProject.service3.Service3Impl.internal_static_CinemaProject_ReserveSeatRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CinemaProject.service3.ReserveSeatRequest.class, CinemaProject.service3.ReserveSeatRequest.Builder.class);
    }

    // Construct using CinemaProject.service3.ReserveSeatRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      ticketId_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return CinemaProject.service3.Service3Impl.internal_static_CinemaProject_ReserveSeatRequest_descriptor;
    }

    @java.lang.Override
    public CinemaProject.service3.ReserveSeatRequest getDefaultInstanceForType() {
      return CinemaProject.service3.ReserveSeatRequest.getDefaultInstance();
    }

    @java.lang.Override
    public CinemaProject.service3.ReserveSeatRequest build() {
      CinemaProject.service3.ReserveSeatRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public CinemaProject.service3.ReserveSeatRequest buildPartial() {
      CinemaProject.service3.ReserveSeatRequest result = new CinemaProject.service3.ReserveSeatRequest(this);
      result.ticketId_ = ticketId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof CinemaProject.service3.ReserveSeatRequest) {
        return mergeFrom((CinemaProject.service3.ReserveSeatRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(CinemaProject.service3.ReserveSeatRequest other) {
      if (other == CinemaProject.service3.ReserveSeatRequest.getDefaultInstance()) return this;
      if (other.getTicketId() != 0) {
        setTicketId(other.getTicketId());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      CinemaProject.service3.ReserveSeatRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (CinemaProject.service3.ReserveSeatRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int ticketId_ ;
    /**
     * <code>int32 ticketId = 1;</code>
     */
    public int getTicketId() {
      return ticketId_;
    }
    /**
     * <code>int32 ticketId = 1;</code>
     */
    public Builder setTicketId(int value) {
      
      ticketId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 ticketId = 1;</code>
     */
    public Builder clearTicketId() {
      
      ticketId_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:CinemaProject.ReserveSeatRequest)
  }

  // @@protoc_insertion_point(class_scope:CinemaProject.ReserveSeatRequest)
  private static final CinemaProject.service3.ReserveSeatRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new CinemaProject.service3.ReserveSeatRequest();
  }

  public static CinemaProject.service3.ReserveSeatRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ReserveSeatRequest>
      PARSER = new com.google.protobuf.AbstractParser<ReserveSeatRequest>() {
    @java.lang.Override
    public ReserveSeatRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ReserveSeatRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ReserveSeatRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ReserveSeatRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public CinemaProject.service3.ReserveSeatRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

