// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TicketingControl.proto

package CinemaProject.service3;

public final class Service3Impl {
  private Service3Impl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CinemaProject_PurchaseTicketRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CinemaProject_PurchaseTicketRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CinemaProject_PurchaseTicketResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CinemaProject_PurchaseTicketResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CinemaProject_ReserveSeatRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CinemaProject_ReserveSeatRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CinemaProject_ReserveSeatResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CinemaProject_ReserveSeatResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CinemaProject_GetMovieScheduleRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CinemaProject_GetMovieScheduleRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CinemaProject_GetMovieScheduleResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CinemaProject_GetMovieScheduleResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CinemaProject_MovieSchedule_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CinemaProject_MovieSchedule_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026TicketingControl.proto\022\rCinemaProject\"" +
      ":\n\025PurchaseTicketRequest\022\017\n\007movieId\030\001 \001(" +
      "\t\022\020\n\010quantity\030\002 \001(\005\":\n\026PurchaseTicketRes" +
      "ponse\022\016\n\006status\030\001 \001(\t\022\020\n\010ticketId\030\002 \001(\005\"" +
      "&\n\022ReserveSeatRequest\022\020\n\010ticketId\030\001 \001(\005\"" +
      "%\n\023ReserveSeatResponse\022\016\n\006status\030\001 \001(\t\"\031" +
      "\n\027GetMovieScheduleRequest\"P\n\030GetMovieSch" +
      "eduleResponse\0224\n\016movieSchedules\030\001 \003(\0132\034." +
      "CinemaProject.MovieSchedule\"S\n\rMovieSche" +
      "dule\022\r\n\005title\030\001 \001(\t\022\017\n\007movieId\030\002 \001(\t\022\020\n\010" +
      "showtime\030\003 \001(\t\022\020\n\010screenId\030\004 \001(\0052\254\002\n\020Tic" +
      "ketingControl\022]\n\016PurchaseTicket\022$.Cinema" +
      "Project.PurchaseTicketRequest\032%.CinemaPr" +
      "oject.PurchaseTicketResponse\022T\n\013ReserveS" +
      "eat\022!.CinemaProject.ReserveSeatRequest\032\"" +
      ".CinemaProject.ReserveSeatResponse\022c\n\020Ge" +
      "tMovieSchedule\022&.CinemaProject.GetMovieS" +
      "cheduleRequest\032\'.CinemaProject.GetMovieS" +
      "cheduleResponseB(\n\026CinemaProject.service" +
      "3B\014Service3ImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_CinemaProject_PurchaseTicketRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CinemaProject_PurchaseTicketRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CinemaProject_PurchaseTicketRequest_descriptor,
        new java.lang.String[] { "MovieId", "Quantity", });
    internal_static_CinemaProject_PurchaseTicketResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CinemaProject_PurchaseTicketResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CinemaProject_PurchaseTicketResponse_descriptor,
        new java.lang.String[] { "Status", "TicketId", });
    internal_static_CinemaProject_ReserveSeatRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_CinemaProject_ReserveSeatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CinemaProject_ReserveSeatRequest_descriptor,
        new java.lang.String[] { "TicketId", });
    internal_static_CinemaProject_ReserveSeatResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_CinemaProject_ReserveSeatResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CinemaProject_ReserveSeatResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_CinemaProject_GetMovieScheduleRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_CinemaProject_GetMovieScheduleRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CinemaProject_GetMovieScheduleRequest_descriptor,
        new java.lang.String[] { });
    internal_static_CinemaProject_GetMovieScheduleResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_CinemaProject_GetMovieScheduleResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CinemaProject_GetMovieScheduleResponse_descriptor,
        new java.lang.String[] { "MovieSchedules", });
    internal_static_CinemaProject_MovieSchedule_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_CinemaProject_MovieSchedule_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CinemaProject_MovieSchedule_descriptor,
        new java.lang.String[] { "Title", "MovieId", "Showtime", "ScreenId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
